### ISSUE TITLE
pom.xml in spring-rest-example seems to be outdated in mvn version and jenkins job failed

### ISSUE THREAD

**Issue by samperay** [pattabhia/examples#3]
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" │
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.x│
sd"> `

while building the job from Jenkins, couldn't build due to older version of maven reference in the pom.xml file. 

==============

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.514 s
[INFO] Finished at: 2020-01-07T06:06:09+00:00
[INFO] Final Memory: 22M/55M
[INFO] ------------------------------------------------------------------------
**[ERROR] No plugin found for prefix 'https' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/lib/jenkins/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE**

**Comment by pattabhia** [comment]
Fixed
